"""Shared helper functions of generated addons.

Nodes use them through `ctx.helper(name)`. Used helpers are written to
`_sn_helpers.py` in the generated addon. A helper can behave differently in
the live (dev) addon than in an exported one; this is the only place where
dev and export builds differ, nodes never check the build mode.
"""

from dataclasses import dataclass


@dataclass
class Helper:
    # source of the function in dev builds
    dev: str
    # source in exported builds, or None to use `export_name` instead
    export: str | None = None
    # name to call in exported builds instead of importing the helper
    export_name: str | None = None


HELPERS = {
    "sn_print": Helper(
        dev='''
def sn_print(*args):
    """print() that also shows the message in the Scripting Nodes editor."""
    import bpy

    message = " ".join(str(arg) for arg in args)
    print(message)
    overlay = bpy.app.driver_namespace.get("_sn_overlay_log")
    if overlay:
        overlay("INFO", message)
''',
        export_name="print",
    ),
}


def source(names, dev: bool) -> str:
    parts = ['"""Generated by Scripting Nodes."""\n']
    for name in sorted(names):
        helper = HELPERS[name]
        code = helper.dev if dev else helper.export
        if code:
            parts.append(code.strip() + "\n")
    return "\n\n".join(parts)


def needs_import(name: str, dev: bool) -> bool:
    helper = HELPERS[name]
    return dev or helper.export is not None


def call_name(name: str, dev: bool) -> str:
    helper = HELPERS[name]
    if not dev and helper.export is None and helper.export_name:
        return helper.export_name
    return name
