schema_version = "1.0.0"

id = "blender_scripting_nodes"
version = "3.4.0"
name = "Serpens"
tagline = "Scripting Nodes for Blender"
maintainer = "Joshua Knauber"
type = "add-on"

website = "https://joshuaknauber.notion.site/Serpens-Documentation-d44c98df6af64d7c9a7925020af11233"

tags = ["Node", "User Interface"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]