# Dev Config: Launch using `python .\scripts\dev.py`
BLENDER_EXECUTABLE: 'C:\Users\Joshua\Desktop\Files\Apps\Blender\blender-4.3.2-windows-x64\blender-4.3.2-windows-x64\blender.exe'
ADDONS_PATH: 'C:\Users\Joshua\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons'